version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-test-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: tests/Postman_Echo.postman_collection.json
          folder: Utilities
workflows:
  version: 2
  workflow:
    jobs:
    - newman-test-run