version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-test-run:
    description: Run API Tests Using Newman
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: tests/Postman_Echo.postman_collection.json
          folder: Utilities
          additional-options: -r cli,junit --reporter-junit-export test-report
      - store_test_results:
        path: test-report
workflows:
  version: 2
  workflow:
    jobs:
    - newman-test-run